CREATE TABLE users (
  id int unsigned NOT NULL AUTO_INCREMENT,
  name varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  email varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  email_verified_at timestamp NULL DEFAULT NULL,
  password varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  apple_token text COLLATE utf8_unicode_ci,
  first_name varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  last_name varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  provider varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'email',
  provider_id varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0000000000000000',
  provider_photo varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0000000000000000',
  photo_url varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  cover_url varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  api_token varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  push_token varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  phone varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  remember_token varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY users_email_unique (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;